version: "3.9"

services:
  backend:
    build: .
    container_name: ai-test-backend

    ports:
      - "8000:8000"

    volumes:
      - ./repo:/app/repo
      - ./chroma_polyglot_storage:/app/chroma_polyglot_storage

    restart: always