"""
LLM Service — pluggable, OpenAI-compatible LLM integration layer.

Architecture
------------
All LLM providers implement the ``LLMProvider`` abstract base class.  A
singleton ``LLMRouter`` selects and caches the active provider at startup
based on the ``LLM_PROVIDER`` environment variable.

Supported providers (out of the box)
-------------------------------------
``openai``    — OpenAI Chat Completions API (gpt-4o, gpt-4-turbo, etc.)
``azure``     — Azure OpenAI (same API, different base URL + api-version)
``ollama``    — Local Ollama server (OpenAI-compatible endpoint)
``mock``      — Deterministic stub for tests and CI (no external calls)

All providers share the same ``LLMRequest`` / ``LLMResponse`` data contracts
so the caller never needs to know which backend is active.

Adding a new provider
---------------------
1. Subclass ``LLMProvider``.
2. Implement ``complete(request) -> LLMResponse``.
3. Register the class in ``_PROVIDER_REGISTRY``.
4. Set ``LLM_PROVIDER=<your_key>`` in the environment.

Environment variables
---------------------
LLM_PROVIDER            openai | azure | ollama | mock   (default: mock)
OPENAI_API_KEY          Required for openai / azure
OPENAI_MODEL            Model name                       (default: gpt-4o-mini)
OPENAI_BASE_URL         Custom base URL (azure / ollama)
AZURE_API_VERSION       Azure API version string         (default: 2024-02-01)
LLM_TEMPERATURE         Sampling temperature             (default: 0.2)
LLM_MAX_TOKENS          Max output tokens                (default: 4096)
LLM_TIMEOUT_SECONDS     HTTP request timeout             (default: 120)
LLM_MAX_RETRIES         Retry count on transient errors  (default: 3)
"""

from __future__ import annotations

import logging
import os
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data contracts
# ---------------------------------------------------------------------------

@dataclass
class LLMMessage:
    """A single chat message (system / user / assistant)."""
    role: str    # "system" | "user" | "assistant"
    content: str


@dataclass
class LLMRequest:
    """Fully specified request sent to the LLM provider."""
    messages: list[LLMMessage]
    temperature: float = 0.2
    max_tokens: int = 4096
    model: str = ""                # Falls back to provider default when empty.
    stop: list[str] = field(default_factory=list)
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class LLMResponse:
    """Normalised response from any LLM provider."""
    content: str                   # The generated text.
    model: str                     # Model that produced the response.
    provider: str                  # Provider name ("openai", "ollama", …).
    prompt_tokens: int = 0
    completion_tokens: int = 0
    latency_ms: int = 0
    finish_reason: str = "stop"
    generated_at: str = field(
        default_factory=lambda: datetime.now(tz=timezone.utc).isoformat()
    )


# ---------------------------------------------------------------------------
# Abstract provider interface
# ---------------------------------------------------------------------------

class LLMProvider(ABC):
    """Base class for all LLM backend adapters."""

    name: str = "base"

    @abstractmethod
    def complete(self, request: LLMRequest) -> LLMResponse:
        """Send *request* to the backend and return a normalised response.

        Args:
            request: Fully populated ``LLMRequest``.

        Returns:
            ``LLMResponse`` with at minimum ``content`` and ``model`` set.

        Raises:
            RuntimeError: On unrecoverable backend errors after retries.
        """


# ---------------------------------------------------------------------------
# Provider: Mock (deterministic, zero-latency — for tests/CI)
# ---------------------------------------------------------------------------

class MockLLMProvider(LLMProvider):
    """Deterministic stub that echoes the prompt back as a valid test file.

    Use this provider in unit tests, CI pipelines without API keys, or
    during local development when you only need the pipeline to run without
    a real LLM call.

    Set ``LLM_PROVIDER=mock`` in your ``.env`` to activate.
    """

    name = "mock"

    # Language → minimal valid test file template
    _TEMPLATES: dict[str, str] = {
        "python": (
            "# [MOCK] Auto-generated by MockLLMProvider\n"
            "import pytest\n\n"
            "def test_placeholder():\n"
            "    \"\"\"Replace with real assertions.\"\"\"\n"
            "    assert True\n"
        ),
        "javascript": (
            "// [MOCK] Auto-generated by MockLLMProvider\n"
            "describe('placeholder', () => {\n"
            "  it('should pass', () => {\n"
            "    expect(true).toBe(true);\n"
            "  });\n"
            "});\n"
        ),
        "typescript": (
            "// [MOCK] Auto-generated by MockLLMProvider\n"
            "describe('placeholder', () => {\n"
            "  it('should pass', () => {\n"
            "    expect(true).toBe(true);\n"
            "  });\n"
            "});\n"
        ),
        "java": (
            "// [MOCK] Auto-generated by MockLLMProvider\n"
            "import org.junit.jupiter.api.Test;\n"
            "import static org.junit.jupiter.api.Assertions.*;\n\n"
            "class PlaceholderTest {\n"
            "    @Test\n"
            "    void placeholder() {\n"
            "        assertTrue(true);\n"
            "    }\n"
            "}\n"
        ),
    }

    def complete(self, request: LLMRequest) -> LLMResponse:
        # Detect the language from the system message content.
        system_content = " ".join(
            m.content.lower() for m in request.messages if m.role == "system"
        )
        language = "python"  # sensible default
        for lang in ("javascript", "typescript", "java"):
            if lang in system_content:
                language = lang
                break

        content = self._TEMPLATES.get(language, self._TEMPLATES["python"])
        logger.debug("[mock_llm] Returning mock %s test template.", language)
        return LLMResponse(
            content=content,
            model="mock-1.0",
            provider=self.name,
            prompt_tokens=len(" ".join(m.content for m in request.messages).split()),
            completion_tokens=len(content.split()),
            latency_ms=0,
        )


# ---------------------------------------------------------------------------
# Provider: OpenAI (and Azure / Ollama via compatible base URL)
# ---------------------------------------------------------------------------

class OpenAIProvider(LLMProvider):
    """OpenAI Chat Completions provider.

    Also works for:
    - **Azure OpenAI** — set ``OPENAI_BASE_URL`` to your Azure endpoint and
      ``AZURE_API_VERSION`` to the desired API version.
    - **Ollama** — set ``OPENAI_BASE_URL=http://localhost:11434/v1`` and use
      any model name available in your Ollama installation.
    - **Any other OpenAI-compatible server** — just point ``OPENAI_BASE_URL``
      at it.

    Retry strategy: exponential back-off for rate-limit (429) and server (5xx)
    errors, up to ``LLM_MAX_RETRIES`` attempts.
    """

    name = "openai"

    def __init__(
        self,
        api_key: str,
        model: str = "gpt-4o-mini",
        base_url: str | None = None,
        api_version: str | None = None,
        temperature: float = 0.2,
        max_tokens: int = 4096,
        timeout: int = 120,
        max_retries: int = 3,
    ) -> None:
        self._api_key = api_key
        self._model = model
        self._base_url = base_url
        self._api_version = api_version  # Azure only
        self._temperature = temperature
        self._max_tokens = max_tokens
        self._timeout = timeout
        self._max_retries = max_retries

        # Lazy-import openai to avoid hard dependency when using other providers.
        try:
            import openai  # type: ignore[import-untyped]
            kwargs: dict[str, Any] = {
                "api_key": api_key,
                "timeout": timeout,
                "max_retries": 0,   # We handle retries ourselves.
            }
            if base_url:
                kwargs["base_url"] = base_url
            if api_version:
                # Azure uses AzureOpenAI client
                from openai import AzureOpenAI  # type: ignore[import-untyped]
                kwargs["azure_endpoint"] = base_url or ""
                kwargs["api_version"] = api_version
                self._client = AzureOpenAI(**kwargs)
                self.name = "azure"
            else:
                self._client = openai.OpenAI(**kwargs)
        except ImportError as exc:
            raise RuntimeError(
                "openai package is not installed. "
                "Run: pip install openai"
            ) from exc

    def complete(self, request: LLMRequest) -> LLMResponse:
        """Send a chat completion request with exponential back-off retries.

        Args:
            request: The ``LLMRequest`` to send.

        Returns:
            Populated ``LLMResponse``.

        Raises:
            RuntimeError: After all retries are exhausted.
        """
        import openai  # type: ignore[import-untyped]

        model = request.model or self._model
        messages = [{"role": m.role, "content": m.content} for m in request.messages]

        last_exc: Exception | None = None
        for attempt in range(1, self._max_retries + 1):
            t0 = time.monotonic()
            try:
                kwargs: dict[str, Any] = {
                    "model": model,
                    "messages": messages,
                    "temperature": request.temperature or self._temperature,
                    "max_tokens": request.max_tokens or self._max_tokens,
                }
                if request.stop:
                    kwargs["stop"] = request.stop
                kwargs.update(request.extra)

                resp = self._client.chat.completions.create(**kwargs)
                latency = int((time.monotonic() - t0) * 1000)

                choice = resp.choices[0]
                usage = resp.usage

                logger.info(
                    "[llm_service] %s → tokens: prompt=%d completion=%d latency=%dms",
                    model,
                    usage.prompt_tokens if usage else 0,
                    usage.completion_tokens if usage else 0,
                    latency,
                )
                return LLMResponse(
                    content=choice.message.content or "",
                    model=resp.model,
                    provider=self.name,
                    prompt_tokens=usage.prompt_tokens if usage else 0,
                    completion_tokens=usage.completion_tokens if usage else 0,
                    latency_ms=latency,
                    finish_reason=choice.finish_reason or "stop",
                )

            except openai.RateLimitError as exc:
                last_exc = exc
                wait = 2 ** attempt
                logger.warning(
                    "[llm_service] Rate limit on attempt %d/%d — sleeping %ds.",
                    attempt, self._max_retries, wait,
                )
                time.sleep(wait)
            except openai.APIStatusError as exc:
                last_exc = exc
                if exc.status_code and exc.status_code < 500:
                    # 4xx errors (except 429) are not retryable.
                    raise RuntimeError(
                        f"OpenAI API error {exc.status_code}: {exc.message}"
                    ) from exc
                wait = 2 ** attempt
                logger.warning(
                    "[llm_service] Server error %d on attempt %d/%d — sleeping %ds.",
                    exc.status_code, attempt, self._max_retries, wait,
                )
                time.sleep(wait)
            except Exception as exc:  # noqa: BLE001
                last_exc = exc
                logger.exception("[llm_service] Unexpected error on attempt %d: %s", attempt, exc)
                if attempt >= self._max_retries:
                    break
                time.sleep(2 ** attempt)

        raise RuntimeError(
            f"LLM request failed after {self._max_retries} attempt(s). "
            f"Last error: {last_exc}"
        ) from last_exc


# ---------------------------------------------------------------------------
# Provider registry + factory
# ---------------------------------------------------------------------------

_PROVIDER_REGISTRY: dict[str, type[LLMProvider]] = {
    "mock":       MockLLMProvider,
    "openai":     OpenAIProvider,
    "azure":      OpenAIProvider,   # Same class, different env config
    "ollama":     OpenAIProvider,   # Same class, local base URL
}


def _build_openai_provider(provider_name: str) -> OpenAIProvider:
    """Construct an ``OpenAIProvider`` from environment variables.

    Args:
        provider_name: "openai" | "azure" | "ollama"

    Returns:
        Configured ``OpenAIProvider`` instance.

    Raises:
        RuntimeError: If required env vars are missing.
    """
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if provider_name in {"openai", "azure"} and not api_key:
        raise RuntimeError(
            f"OPENAI_API_KEY is required for LLM_PROVIDER={provider_name}. "
            "Set it in your .env file."
        )

    model = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
    base_url: str | None = os.environ.get("OPENAI_BASE_URL") or None
    api_version: str | None = None
    if provider_name == "azure":
        api_version = os.environ.get("AZURE_API_VERSION", "2024-02-01")
    if provider_name == "ollama":
        base_url = base_url or "http://localhost:11434/v1"
        api_key = api_key or "ollama"  # Ollama ignores the key but requires a value

    return OpenAIProvider(
        api_key=api_key,
        model=model,
        base_url=base_url,
        api_version=api_version,
        temperature=float(os.environ.get("LLM_TEMPERATURE", "0.2")),
        max_tokens=int(os.environ.get("LLM_MAX_TOKENS", "4096")),
        timeout=int(os.environ.get("LLM_TIMEOUT_SECONDS", "120")),
        max_retries=int(os.environ.get("LLM_MAX_RETRIES", "3")),
    )


def build_provider(provider_name: str | None = None) -> LLMProvider:
    """Instantiate the LLM provider specified by *provider_name* (or ``LLM_PROVIDER`` env var).

    Args:
        provider_name: Override the environment variable if provided.

    Returns:
        A ready-to-use ``LLMProvider`` instance.

    Raises:
        ValueError: For unknown provider names.
        RuntimeError: For misconfigured providers.
    """
    name = (provider_name or os.environ.get("LLM_PROVIDER", "mock")).lower().strip()

    if name not in _PROVIDER_REGISTRY:
        raise ValueError(
            f"Unknown LLM_PROVIDER='{name}'. "
            f"Available: {sorted(_PROVIDER_REGISTRY.keys())}"
        )

    if name == "mock":
        return MockLLMProvider()

    if name in {"openai", "azure", "ollama"}:
        return _build_openai_provider(name)

    # Future custom providers instantiated with no args.
    return _PROVIDER_REGISTRY[name]()


# ---------------------------------------------------------------------------
# Module-level singleton (lazy-initialised)
# ---------------------------------------------------------------------------

_provider_cache: LLMProvider | None = None


def get_provider() -> LLMProvider:
    """Return the cached LLM provider, creating it on first call.

    Thread-safe for read-heavy workloads (Python GIL protects simple
    assignment).  For multi-process Celery workers, each process gets its
    own cache — this is correct behaviour.

    Returns:
        The active ``LLMProvider`` instance.
    """
    global _provider_cache  # noqa: PLW0603
    if _provider_cache is None:
        _provider_cache = build_provider()
        logger.info("[llm_service] Initialised provider: %s", _provider_cache.name)
    return _provider_cache


def reset_provider(provider: LLMProvider | None = None) -> None:
    """Replace or clear the cached provider (used in tests).

    Args:
        provider: New provider to cache, or None to force re-initialisation
                  on the next ``get_provider()`` call.
    """
    global _provider_cache  # noqa: PLW0603
    _provider_cache = provider
    logger.debug("[llm_service] Provider cache reset to: %s", provider)


# ---------------------------------------------------------------------------
# High-level helper
# ---------------------------------------------------------------------------

def complete(
    system_prompt: str,
    user_prompt: str,
    *,
    temperature: float | None = None,
    max_tokens: int | None = None,
    model: str = "",
) -> LLMResponse:
    """Send a two-message (system + user) chat completion request.

    This is the primary call-site used by ``test_generation_service``.
    Callers never need to construct ``LLMRequest`` / ``LLMMessage`` directly.

    Args:
        system_prompt: The system instruction (role and constraints).
        user_prompt:   The user message (diff, context, task).
        temperature:   Override the provider default sampling temperature.
        max_tokens:    Override the provider default max output tokens.
        model:         Override the provider default model name.

    Returns:
        ``LLMResponse`` with generated test content in ``.content``.
    """
    provider = get_provider()
    request = LLMRequest(
        messages=[
            LLMMessage(role="system", content=system_prompt),
            LLMMessage(role="user", content=user_prompt),
        ],
        temperature=temperature if temperature is not None else 0.2,
        max_tokens=max_tokens if max_tokens is not None else 4096,
        model=model,
    )
    logger.debug(
        "[llm_service] complete() provider=%s model=%s prompt_chars=%d",
        provider.name, model or "(default)", len(system_prompt) + len(user_prompt),
    )
    return provider.complete(request)
