"""PR summary agent for structured pull request messaging."""

from __future__ import annotations

import logging
from dataclasses import dataclass


logger = logging.getLogger(__name__)


@dataclass
class PullRequestSummary:
    title: str
    body: str


def build_pr_summary(repo_name: str, stats: dict[str, int], validation_status: str) -> PullRequestSummary:
    """Build a PR summary from generation stats and validation results."""

    logger.info("[pr_agent] Building PR summary for %s", repo_name)
    title = f"chore(tests): update automated tests for {repo_name}"
    body = (
        "## Automated Test Update\n"
        f"- Total prompts: {stats.get('total_prompts', 0)}\n"
        f"- Changed files: {stats.get('changed_files', 0)}\n"
        f"- Functions changed: {stats.get('functions_changed', 0)}\n"
        f"- Validation: {validation_status}\n"
        "\nGenerated by the autonomous testing platform."
    )
    return PullRequestSummary(title=title, body=body)
